// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsBrwCfqevBYVDK889b6ZlJ79WhJUBhOc',
    appId: '1:153020199339:android:8a558a11fd3a6c248962ee',
    messagingSenderId: '153020199339',
    projectId: 'buddy-hanse-240911-1d091',
    storageBucket: 'buddy-hanse-240911-1d091.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpTW8kEBOwDA89ws2u5HaRuZUP1IyEKvE',
    appId: '1:153020199339:web:c4b6af31a89382fc8962ee',
    messagingSenderId: '153020199339',
    projectId: 'buddy-hanse-240911-1d091',
    authDomain: 'buddy-hanse-240911-1d091.firebaseapp.com',
    storageBucket: 'buddy-hanse-240911-1d091.appspot.com',
    measurementId: 'G-THJ3RG6K62',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpTW8kEBOwDA89ws2u5HaRuZUP1IyEKvE',
    appId: '1:153020199339:web:76a4237872128a9d8962ee',
    messagingSenderId: '153020199339',
    projectId: 'buddy-hanse-240911-1d091',
    authDomain: 'buddy-hanse-240911-1d091.firebaseapp.com',
    storageBucket: 'buddy-hanse-240911-1d091.appspot.com',
    measurementId: 'G-QFMVCDG9N6',
  );

}